### ISSUE TITLE
Unintentionally forced to use treesitter

### ISSUE THREAD

**Issue by tani** [CopilotC-Nvim/CopilotChat.nvim#142]
On the canary branch we need to use treesitter.
In lua/CopilotChat/diff.lua, the create_buf function calls `vim.treesitter.start`.
On the stable branch we did not do this. I would like to disable the treesitter.
Would you consider this?

**Comment by deathbeam** [comment]
Builtin LSP info like LSP hover functions exactly like this already as well, it enables treesitter only for that buffer and as that filetype so why?

**Comment by tani** [comment]
I usually use neovim without installing nvim-treesitter/nvim-treesitter in the package manager. And even in that case, builtin-lsp works well, and I expect it to work the same way with CopilotChat.
However, CopilotChat asks for markdown and diff parsers and outputs an error because it can't find them.

You are right that Treesitter is useful and I agree with you. However, I stopped using treesitter for a while after experiencing a few disruptive API changes by treesitter that made my neovim not work properly.
If possible, could you please make it possible for users like me to opt out of treesitter?

**Comment by tani** [comment]
I don't want treesitter disabled, I want an option to work in the absence of treesitter. Thank you for your kind reply.

**Comment by deathbeam** [comment]
So is it throwing errors on both markdown and diff parsers or only on diff? Because this do not relies on nvim-treesitter, just built-in treesitter stuff. And I believe neovim ships with markdown parser by default because of the lsp stuff but maybe it doesnt ship with diff. Could you show screenshot of `vim.lsp.buf.hover()` maybe?

**Comment by deathbeam** [comment]
Fixed in 2103222

**Comment by tani** [comment]
Thank you so much!
