### ISSUE TITLE
Feature request: Combined show_prompt_actions and show_help_actions

### ISSUE THREAD

**Issue by Andrej-Marsic** [CopilotC-Nvim/CopilotChat.nvim#146]
Is there a way to combine both of those under a single command, like `show_actions`?

I don't think I have enough help actions to warrant for its own shortcut, so I would like to have them together with the prompt actions.

**Comment by deathbeam** [comment]
You can do this already on `canary` by joining the both arrays I believe. E.g

```lua
local actions = require("CopilotChat.actions")
local combined = actions.help_actions()
combined = vim.tbl_deep_extend('force', actions.prompt_actions())
require("CopilotChat.integrations.telescope").pick(combined)
```

**Comment by jellydn** [comment]
Hi @Andrej-Marsic 
Re. the `help actions`, I introduced this API to our plugin as I want to have something similar to VS Code. 

<img width="722" alt="image" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/870029/72c026c8-59c7-44a7-8785-5d5a3607b984">

The `help actions` are only available if there is a `diagnostic issue` at the current line.

The `prompt actions` is the pre-defined prompt for your needs which is not the same use cases with `help actions`. I don't think we should merge those however technically, you could do as @deathbeam's comment.

**Comment by Andrej-Marsic** [comment]
Adding my implementation of @deathbeam's suggestion above:
```lua
local actions = require("CopilotChat.actions")
local prompt_actions = actions.prompt_actions() or {}
local help_actions = actions.help_actions() or {}
local combined = vim.tbl_deep_extend("force", prompt_actions, help_actions)
require("CopilotChat.integrations.telescope").pick(combined)
```
Thanks :)
