### ISSUE TITLE
Feature Request: Saving current chat

### ISSUE THREAD

**Issue by BlueDruddigon** [CopilotC-Nvim/CopilotChat.nvim#167]
Hello, it's BlueD.

I'm presently utilizing this repository alongside `lazy.nvim`, and I must say, I'm thoroughly pleased with it. The sole disparity I've noticed between this repository and the original Github Copilot Chat plugin for VSCode is the latter's ability to save ongoing chats upon closure and restore them upon reopening. Consequently, I would like to propose the implementation of this feature in neovim.

Appreciatively,
BlueD

**Comment by deathbeam** [comment]
Hello. You mean on closing whole neovim or just closing the chat window?

**Comment by BlueDruddigon** [comment]
> Hello. You mean on closing whole neovim or just closing the chat window?

Thank for your reply.

I mean actually closing whole neovim!

Regards, BlueD
