### ISSUE TITLE
Telescope prompt_actions not use select.gitdiff selection

### ISSUE THREAD

**Issue by letieu** [CopilotC-Nvim/CopilotChat.nvim#206]
```lua
local actions = require "CopilotChat.actions"
require("CopilotChat.integrations.telescope").pick(actions.prompt_actions())
```

When i run above code, it show list prompt action, but when choose `Commit` or `CommitStaged`, it open chat window window but with `visual` selection, not `gitdiff`

It work fine if I use command `:CopilotChatCommit`

**Comment by letieu** [comment]
@all-contributors please add @letieu  for bug

Just try if I can hack bot

**Comment by deathbeam** [comment]
Lol. Thats not very smart bot for sure :d
