### ISSUE TITLE
[Feature] remove first line break

### ISSUE THREAD

**Issue by sand4rt** [CopilotC-Nvim/CopilotChat.nvim#209]
Would it be possible to remove the first blank line? as the spacing looks kind of odd:

Current:
<img width="1911" alt="Screenshot 2024-03-20 at 15 55 01" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/17591696/b62e2b74-fd50-4350-af79-7431b1e87420">

Desired:
<img width="1911" alt="Screenshot 2024-03-20 at 15 55 44" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/17591696/4a68b1c0-f6e9-43f9-9bee-790b9fa6764d">

**Comment by deathbeam** [comment]
Sadly because of how extmarks work (or dont rly work) in neovim the first empty line is necessary so we can put help content below it (as when I tried to use `above` extmark its all kinds of broken).

If extmark `above` ever starts working properly we could remove the empty line.

**Comment by sand4rt** [comment]
This issue is fixed
