### ISSUE TITLE
Feature request add line numbers to buffer selection

### ISSUE THREAD

**Issue by aweis89** [CopilotC-Nvim/CopilotChat.nvim#214]
I noticed when prompting, using buffer as the selection, copilot often mixes up the correct line numbers when it references it in the prompt or response.
It seems like when adding line numbers to the selection it's no longer an issue.
Given that referencing lines may be a common use-case, perhaps we should change the default?

**Comment by deathbeam** [comment]
Hmm, the issue with prepending the line numbers is that it might confuse copilot more often than it will help?Im actually not sure. Because we are sending it as code block its no longer valid code (and it will also not be displayed well at all in show user selection menu)

**Comment by jellydn** [comment]
Just FYI @gptlang Any thoughts on this?

**Comment by aweis89** [comment]
For some additional context, I first noticed this issue when asking questions about line X. But where it really started becoming an issue when I integrated it as a linter:

```lua
```

**Comment by deathbeam** [comment]
I think another possible solution would be to simply tell copilot the line range as part of the `Active selection` we are sending. I think that is quite doable,I will take a look and see if it helps.But yea that use case is pretty neat

**Comment by aweis89** [comment]
> I think another possible solution would be to simply tell copilot the line range as part of the `Active selection` we are sending. I think that is quite doable,I will take a look and see if it helps.But yea that use case is pretty neat

Although notably, the issue happens when the selection is set to the entire buffer (with no line numbers) rather than just with a sub-selection of the file, which lead me to think copilot is just not that good at counting lines

**Comment by deathbeam** [comment]
Yea that is why I think maybe providing line range would help. Atm we basically do

Active Selection: `filename`
```filetype
contents
```

so can easily add also line range there I guess

**Comment by aweis89** [comment]
> Yea that is why I think maybe providing line range would help. Atm we basically do
> 
> Active Selection: `filename`
> 
> ```
> contents
> ```
> 
> so can easily add also line range there I guess

I can give that a shot and report back

**Comment by deathbeam** [comment]
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/5115805/7934d78a-b56a-4f43-81b0-d898cdcd54f2)

Actually already did locally. Looks like copilot understands somewhat. And thats with partial selection

**Comment by deathbeam** [comment]
Could you try with this? https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/217

There can probs be some improvements but it needs to be appended only like this at the very end to not break showing diffs and user selection. Technically this can also prepend the line numbers as user's do not see this at all so if that will be necessary can be done when building the Active selection I guess

**Comment by aweis89** [comment]
> Could you try with this? #217
> 
> There can probs be some improvements but it needs to be appended only like this at the very end to not break showing diffs and user selection. Technically this can also prepend the line numbers as user's do not see this at all so if that will be necessary can be done when building the Active selection I guess

Unfortunately it seems to still get all the lines wrong in my example prompt

**Comment by deathbeam** [comment]
> > Could you try with this? #217
> > There can probs be some improvements but it needs to be appended only like this at the very end to not break showing diffs and user selection. Technically this can also prepend the line numbers as user's do not see this at all so if that will be necessary can be done when building the Active selection I guess
> 
> Unfortunately it seems to still get all the lines wrong in my example prompt (when not adding the lines prefix to each line)

Hmm, I willtry adjusting the line numbers then in selection

**Comment by deathbeam** [comment]
Alright tried your snippet just now and I think it works and user doent know about the lines being added either. Was also testing some diffing and I think it works fine still

**Comment by aweis89** [comment]
> Alright tried your snippet just now and I think it works and user doent know about the lines being added either. Was also testing some diffing and I think it works fine still

It's much better however:
I noticed it has a consistent off by one error (diagnostics appear one line bellow).
On my ~300 line file, it also made two mistakes where it was off 3-4 lines.
When I add line numbers to this branch it gets all confused, presumably because they don't match up.
Adding line number prefixes seems more consistent on my brief test (~300 line lua file)

**Comment by deathbeam** [comment]
Yea I adjusted your snippet when I was trying it and just used select.buffer as selection as the line numbers are already being added there so you can't add them second time.

I just tried it again and tried to pay closer attention and you are right its consistently off by 1 which is weird, I will try to debug that

**Comment by deathbeam** [comment]
Alright did some changes to both main system prompt (as now copilot was sometimes outputting lines) and also the line numbering, looked somewhat consistent to me, can you try again @aweis89

**Comment by aweis89** [comment]
> Btw this snippet is giga neat I will probs keep using it as well, would be also cool to maybe submit it to `Tips` section for the plugin (or maybe we could have discussions section for stuff like this?)

It's almost perfect and certainly good enough imo. It got 17 exactly correct and just one a couple lines off (and the diagnostics below it were all still exactly correct):

```lua
    -- branch = "canary",

    dependencies = {
      { "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
      { "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
    },
    config = function() -- The diagnostic for user_key_mappings showed up here
      load_requirements()

      local user_key_mappings = {

```

The only slightly jenky thing about this snippet is pulling the left window buffer. Perhaps we should add `CopilotChat.config.source` that as a second param to `callback`?

**Comment by deathbeam** [comment]
> > Btw this snippet is giga neat I will probs keep using it as well, would be also cool to maybe submit it to `Tips` section for the plugin (or maybe we could have discussions section for stuff like this?)
> 
> It's almost perfect and certainly good enough imo. It got 17 exactly correct and just one a couple lines off (and the diagnostics below it were all still exactly correct):
> 
> ```lua
>     -- branch = "canary",
> 
>     dependencies = {
>       { "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
>       { "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
>     },
>     config = function() -- The diagnostic for user_key_mappings showed up here
>       load_requirements()
> 
>       local user_key_mappings = {
> ```
> 
> The only slightly jenky thing about this snippet is pulling the left window buffer. Perhaps we should add `CopilotChat.config.source` as a second param to `callback`?

Sure I think that makes a lot of sense

**Comment by aweis89** [comment]
Happy to submit it to the readme or discussions, whatever you prefer.
Discussions might be better in-case lots of other cool examples come up.
That said, folks often don't look there so maybe readme is better 🤷

**Comment by deathbeam** [comment]
> Happy to submit it to the readme or discussions, whatever you prefer. Discussions might be better in-case lots of other cool examples come up. That said, folks often don't look there so maybe readme is better 🤷

Maybe discussions section + link there from README from under tips could work not sure. @jellydn do you think this could be good idea?

**Comment by jellydn** [comment]
> README

Let's use README as it will generate vimdoc and user could search form neovim. Thanks.
