### ISSUE TITLE
`auto_insert_mode` does not start insert mode when opening window

### ISSUE THREAD

**Issue by famiu** [CopilotC-Nvim/CopilotChat.nvim#222]
Setting `auto_insert_mode` to `true` does not seem to start insert mode when opening a new window using `:CopilotChat`. I have tried debugging the issue myself, and it seems like `M.ask()` always calls `M.open()` with `no_focus = true`, and there is an `if not no_focus` check which prevents `startinsert` from being called. I'm not sure if this is intended or not, but the documentation for `auto_insert_mode` suggests otherwise.

**Comment by deathbeam** [comment]
So I assume with CopilotChatOpen it works then. But yea this is my bad, need to check if i should pass that param only if ask prompt is not empty
