### ISSUE TITLE
"attempt to compare string with nil" error

### ISSUE THREAD

**Issue by davidgao7** [CopilotC-Nvim/CopilotChat.nvim#224]
[ Error Message ]
<img width="755" alt="Screenshot 2024-03-22 at 10 40 28 AM" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/39502459/2a1cdd26-78f8-480d-b610-c7f471a71154">

<img width="882" alt="Screenshot 2024-03-22 at 10 49 14 AM" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/39502459/76b06206-ec8f-4a6a-bda9-b27566414a23">

Hi
I used lazy.nvim to update the plugin around an hour ago and get this error. I followed [lazy-nvim-ide setup](https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua) to write my copilot_chat.lua config.

[ My setup ]
[Here is my complete copilot chat config](https://github.com/davidgao7/InterviewProblems/blob/master/copilot_chat.lua)

Does anyone know what's going on?

I would appreciate if anyone could help me!

**Comment by jellydn** [comment]
The mapping is the table. You should change as below.

```lua
mappings = {
        -- Use tab for completion
        complete = {
          detail = "Use @<Tab> or /<Tab> for options.",
          insert = "<Tab>",
        },
        -- Close the chat
        close = {
          normal = "q",
          insert = "<C-c>",
        },
        -- Reset the chat buffer
        reset = {
          normal = "<C-l>",
          insert = "<C-l>",
        },
        -- Submit the prompt to Copilot
        submit_prompt = {
          normal = "<CR>",
          insert = "<C-CR>",
        },
        -- Accept the diff
        accept_diff = {
          normal = "<C-y>",
          insert = "<C-y>",
        },
        -- Show the diff
        show_diff = {
          normal = "gmd",
        },
        -- Show the prompt
        show_system_prompt = {
          normal = "gmp",
        },
        -- Show the user selection
        show_user_selection = {
          normal = "gms",
        },
      },
```
