### ISSUE TITLE
bug: Failed to run `config` for CopilotChat.nvim

### ISSUE THREAD

**Issue by petersid2022** [CopilotC-Nvim/CopilotChat.nvim#225]
Hello everyone.

I've been getting this weird bug, upon opening Neovim:
```
Failed to run `config` for CopilotChat.nvim

...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/init.lua:614: attempt to compare two nil values

# stacktrace:
  - /CopilotChat.nvim/lua/CopilotChat/init.lua:614
  - /CopilotChat.nvim/lua/CopilotChat/init.lua:609 _in_ **setup**
  - lua/plugins/configs/copilot.lua:58 _in_ **config**
```

Here's  my lazy config (which is pretty much [this](https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua)):
```lua
return {
    {
        "CopilotC-Nvim/CopilotChat.nvim",
        tag = 'v2.0.0',
        branch = "canary",
        dependencies = {
            { "zbirenbaum/copilot.lua" },
        },
        opts = {
        },
        config = function(_, opts)
        end,
        event = "VeryLazy",
        keys = {
        },
    },
}
```

Where I have to specify ``tag = 'v2.0.0'``, otherwise (if I don't specify that)  lazy will install the latest version of the plugin (tag: ``v2.1.0``) which returns the aforementioned error.

I'm using:
```
NVIM v0.10.0-dev-2659+g47388614c
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
```

**Comment by jellydn** [comment]
Hi, @petersid2022 You should either use `tag = 'v2.0.0' or branch = "canary".

I would suggest to remove `canary` branch and use release version as my config https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua

cc @deathbeam We have 3 reports for breaking change from the mappings PR, fyi.

**Comment by petersid2022** [comment]
Awesome, thanks for the quick reply!

**Comment by deathbeam** [comment]
> Hi, @petersid2022 You should either use `tag = 'v2.0.0' or branch = "canary".
> 
> I would suggest to remove `canary` branch and use release version as my config https://github.com/jellydn/lazy-nvim-ide/blob/main/lua/plugins/extras/copilot-chat-v2.lua
> 
> cc @deathbeam We have 3 reports for breaking change from the mappings PR, fyi.

Yea that was expected. But we can add error message to tell ppl what is happening I think that is good idea,I will open PR
