### ISSUE TITLE
Edgy no longer working

### ISSUE THREAD

**Issue by kevintraver** [CopilotC-Nvim/CopilotChat.nvim#228]
The current version sets **filetype** to `markdown`
https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/f4f607cc52f7abdc8b7bba6126fa767455ff52e4/lua/CopilotChat/chat.lua#L44

Before release 2.0 the **filetype** was set to `copilot-chat`
https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/60718ed6e806fa86fd78cb3bf55a05f1a74b257e/rplugin/python3/CopilotChat/handlers/vsplit_chat_handler.py#L14

**Comment by deathbeam** [comment]
We actually wanted to change this for stuff like nvim-cmp integrations anyway just was waiting for that, but can be done before that as well for sure

**Comment by kevintraver** [comment]
CopilotChat is working again with Edgy now. Thanks!
