### ISSUE TITLE
Syntax highlighting breaks when "footer menu" appears

### ISSUE THREAD

**Issue by sudo-tee** [CopilotC-Nvim/CopilotChat.nvim#239]
Recently I started having issue with syntax highlighting in the chat window.

Everything looks fine when generating the content but as soon as the bottom menu appears the syntax highlighting is broken

Before
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/342110/34c80305-ac08-403b-b241-395d30a47e25)

After
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/342110/5d1528b4-7806-474a-b139-45d9e032540b)

Thanks for your great plugin.

**Comment by sudo-tee** [comment]
I found that it comes from this commit
https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/066e605335ca5d6ac9163b57c9175a9340ee1fa1

If I put the old config

```
 -- Restore the format with ## headers as prefixes,
    question_header = '## User ',
    answer_header = '## Copilot ',
    error_header = '## Error ',
```

The syntax is fine after the generation

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/342110/83131aea-922a-4c56-bfb3-5f5c89dfb6e2)

**Comment by jellydn** [comment]
Thanks @sudo-tee for the report. This probably the upstream issue with `bold` for treesitter.

**Comment by p135246** [comment]
Should the syntax highlighting work out of the box? I don't get any...

**Comment by deathbeam** [comment]
> Should the syntax highlighting work out of the box? I don't get any...

See :checkhealth you might not have treesitter enabled or something

**Comment by deathbeam** [comment]
Technically solved by https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/336 as the default separator was changed from `--` which is markdown horizontal rule to something else so this is no longer an issue by default and as it is upstream issue no reason to keep this open anymore.
