### ISSUE TITLE
gpt-3 is used even if gpt-4 is specified?

### ISSUE THREAD

**Issue by lindelleric** [CopilotC-Nvim/CopilotChat.nvim#245]
I'm using the default configurations that are set internally in the plugin.  So it should default to gpt-4, which I can verify in the debug logs (see image). 

However, when I ask what version it is, it always responds that it's based on gpt-3. 

Any hints on what is going on here?

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/7161066/8e63cc5e-b702-449c-bee6-f3a8d0afbfb7)

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/7161066/c194da9a-84cd-418f-9ac4-8268a0f277af)

**Comment by gptlang** [comment]
It's gpt-4. It just doesn't know it.

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/121417512/321a7bfc-12fb-4e28-bedb-73e1fc6300ca)
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/121417512/7d93940c-aeac-4340-8eb7-037f578b4131)

Training data reasons

**Comment by lindelleric** [comment]
Cool, thanks! A bit odd that it doesn't know. But then again, it doesn't really _gpt-4_ until after the training is complete.

**Comment by jonaustin** [comment]
fwiw, it seems to get it right now:

```
## User ───

what model of gpt are you?

## Copilot ───

I am based on the GPT-4 version of OpenAI's GPT models.
```
