### ISSUE TITLE
<CR> in insert mode submits the prompt instead of inserting a new line

### ISSUE THREAD

**Issue by GuillaumeDesforges** [CopilotC-Nvim/CopilotChat.nvim#246]
When I hit `<CR>` in insert mode in the chat window, it submits.

The only other binding I have on `<CR>` for imap is nvim-cmp.

![Peek 2024-03-28 13-44](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/1882000/c8a2d57f-ea77-4224-9472-24a34b3d60eb)

**Comment by deathbeam** [comment]
I think this is issue with <CR> being translated to <C-m>, i had this exact same issue but I assumed its only for some terminals so i only fixed it in my config

**Comment by GuillaumeDesforges** [comment]
Thank you very much for the speedy response!
