### ISSUE TITLE
Default window layout throws error on canary branch

### ISSUE THREAD

**Issue by Coding-Journey** [CopilotC-Nvim/CopilotChat.nvim#251]
I get this error if I try to run :CopilotChatOpen without setting a window layout:
`Error executing Lua callback: ...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/chat.lua:157: invalid key: vertical
stack traceback:
        [C]: in function 'nvim_open_win'
        ...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/chat.lua:157: in function 'open'
        ...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/init.lua:296: in function <...hare/nvim/lazy/
CopilotChat.nvim/lua/CopilotChat/init.lua:276>`

This error is thrown for: window = { layout = 'vertical' } and window = { layout = 'horizontal' }

The workaround is setting window = { layout = 'float' }

Thought I'd flag as the defaults for a new user don't work

**Comment by jellydn** [comment]
Hi @Coding-Journey Thanks for your report. Could you provide more information about your setup?E.g: run `healthcheck` command

**Comment by TisnKu** [comment]
This happens on Windows but not on Mac.

Nvim version:
NVIM v0.10.0-dev-1801+g2ebd328a7
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
Run "nvim -V1 -v" for more info

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/10512841/2c92c585-454e-42ea-ba93-812057308da8)

**Comment by Coding-Journey** [comment]
This is happening on WSL for me.
Setup:

Windows 11
WSL
Alacritty 0.13.1 (fe2a3c5)
Ubuntu 20.04.3,

NVIM v0.10.0-dev-2046+g9a2c98087
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377

:checkhealth
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/32914183/02222649-77f8-4c59-b755-430d9e6c223c)

**Comment by deathbeam** [comment]
Can you both try to update your neovim nightly versions @TisnKu and @Coding-Journey . Its possible you have old versions of nightly and that is why the `vertical` is not there.

**Comment by Coding-Journey** [comment]
@deathbeam, that was exactly it!

I built from the latest commit (0.10.0-dev-2753+g77d3526a3), defaults and 
then setting vertical/horizontal explicitly worked correctly
