### ISSUE TITLE
Feature Request: Code Generation

### ISSUE THREAD

**Issue by ryoppippi** [CopilotC-Nvim/CopilotChat.nvim#259]
I'd like to generate code in editor prompt like this!
![Screenshot 2024-04-04 at 09 44 28](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/1560508/7ac91f1a-3d29-4fdd-8140-03f87346c014)

**Comment by ryoppippi** [comment]
I think it enough to create a feature to yank/insert command from generated codeblock

**Comment by deathbeam** [comment]
Doesnt this already work? If you use the accept diff feature

**Comment by ryoppippi** [comment]
you mean `<c-y>` to accept diff, right? it does not work for me

**Comment by ryoppippi** [comment]
Oh, okay.
I just wanna generate something new from empty buffer, so applying diff does not work for this case

**Comment by deathbeam** [comment]
I guess there is check for empty string somewhere then,probs easy fix to just remove that then it should work for empty buffer as well

**Comment by ryoppippi** [comment]
Thank you!!
