### ISSUE TITLE
Low internet network will crash nvim (WSL2 Ubuntu)

### ISSUE THREAD

**Issue by chuongxxx** [CopilotC-Nvim/CopilotChat.nvim#262]
I'm using Lazyvim on WSL2 Ubuntu, and Copilot occasionally causes Neovim to freeze while generating the answer. The issue might be due to lag in my internet connection or WSL2. Please advise!

**Comment by deathbeam** [comment]
If your connection is super slow then i can see it as authentication is synchronous so when it tries to get new token (when it expires) it blocks. I can try to make it async and that should solve it
