### ISSUE TITLE
Buffer or buffers as context doesn't seem to work.

### ISSUE THREAD

**Issue by lawlondon** [CopilotC-Nvim/CopilotChat.nvim#263]
Using @buffer or @buffers in the prompt doesn't seem to work but I may be using it wrong. If I use the command CopilotChatExplain @buffer trying to get it to explain the entire buffer it only explains the current line the cursor is on. I tried changing the default context in the config but it returned unknow global 'buffer'.

**Comment by jellydn** [comment]
Hi @lawlondon Could you share your config? Thanks.

**Comment by lawlondon** [comment]
Installed with lazy.nvim with file copilotchat.lua in ~/.config/nvim/lua/plugins/
Other than that I haven't changed the default config.
This is the plugin.lua file:
return {
  {
    "CopilotC-Nvim/CopilotChat.nvim",
    branch = "canary",
    dependencies = {
      { "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
      { "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
    },
    opts = {
      debug = true, -- Enable debugging
      -- See Configuration section for rest
    },
    -- See Commands section for default commands if you want to lazy load on them
  },
}
All dependencies are met.

**Comment by deathbeam** [comment]
Context and selection are both sent at once. Context is used so Copilot knows about what you are asking and selection then as specific excerpt from that context. You can make a prompt that asks about both, but context is mostly just so copilot understands stuff *around* the thing you are asking about. That is what @workspace in vscode does as well. If you want to ask about whole buffer either select the whole file or use `select.buffer` (see README examples)

**Comment by lawlondon** [comment]
Okay, thanks for explaining. Thanks for your time. Hope you have a good one.

**Comment by Madoshakalaka** [comment]
Please reopen this issue. `@buffers` really doesn't seem to work.

I first realized it in my own project but it's reproducible in a simple setup:

Here I have two files open, and I called `:CopilotChat` in the bottom buffer. The copilot was able to answer the question correctly.

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/44753941/fe90f5bd-361a-4427-9170-df77b9be200b)

I repeated a similar question on the top buffer and it was able to answer that correctly. 

But when I use `@buffers`, it seems to not be able to read any buffer at all. (however, the container4 line seems to be read. Maybe cuz I called the command at that line?):

![Screenshot from 2024-04-10 04-44-04](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/44753941/5cce080b-202f-406d-8cb3-99a2626b6677)

Calling `selection = require("CopilotChat.select").buffers` from lua has resulted the same behavior for me.

**Comment by deathbeam** [comment]
@buffers make an outline of the file, @buffer sends the whole file. You can see the outline for current buffer when you use :CopilotChatDebugInfo . But I think with HTML files it just doesnt work as there are no function definitions or class definitions,which is what we use for building the outline
