### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by gmankab** [CopilotC-Nvim/CopilotChat.nvim#28]
so [copilot.vim](https://github.com/github/copilot.vim) supports http proxy

via option in lua:
```lua
vim.g.copilot_proxy = 'localhost:2081'
```

this option allows to use copilot via proxy while all other neovim plugin uses internet without a proxy

and via environment variable:
```bash
export HTTPS_PROXY="https://localhost:2081" ; nvim
```

this environment variable allows to use whole neovim via proxy while all other apps uses internet without a proxy

can you please add something similar to your plugin

**Comment by gptlang** [comment]
I'll take a shot

**Comment by gmankab** [comment]
thank you
