### ISSUE TITLE
Turn off auto complete?

### ISSUE THREAD

**Issue by aramrw** [CopilotC-Nvim/CopilotChat.nvim#291]
When I first set this up it never inline auto completed for me, but I changed some of my other plugins (a while ago) and now it does for some reason.

I'd like to turn it back off again and only be able to use the chat, if someone could tell me how to do that I'd appreciate it 👍🏼 

And by turn it off, I mean I don't want to be able to see them at all, not just remove the shortcut

**Comment by deathbeam** [comment]
There is no autocomplete in the plugin at all. Maybe you mean copilot.vim or copilot.lua autosuggestions? But those are different plugins so refer to their documentation

**Comment by tecfu** [comment]
@aramrw I had this issue as well. For me the problem is that the default completion setting breaks both coc.nvim and nvim-cmp. Try:

```
require('CopilotChat').setup({
    debug = true,
    mappings = {
      complete = {
        detail = 'Use @<Tab> or /<Tab> for options.',
	-- Default <Tab> setting conflicts with cmp and coc-nvim
        insert = '<S-Tab>'
      }
    }
  })
```

**Comment by antonmry** [comment]
In my case, it was a collision with github/copilot.vim, I fixed it removing the mapping:

```lua
  {
    "CopilotC-Nvim/CopilotChat.nvim",
    branch = "canary",
    dependencies = {
      {"github/copilot.vim"},
      { "nvim-lua/plenary.nvim" }, 
    },
    opts = {
      debug = true,
      show_help = false,
      mappings = {
	complete = {
	  insert = '',
	},
      },
    },
  },
```
