### ISSUE TITLE
Text should not wrap when panel width is less than wrap length

### ISSUE THREAD

**Issue by bendavis78** [CopilotC-Nvim/CopilotChat.nvim#292]
This screenshot explains it. Line 4 is wrapped by vim,  but then some kind of auto-wrapping kicks in. I'm fine with auto-wrapping at a certain width, but the wrapping length should be determined by the width of the buffer if it's below the default auto-wrapping width.

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/324392/e374cb38-4e19-4142-98f4-760a1cafe78f)

**Comment by deathbeam** [comment]
Made a PR with a fix, now it will never force wrap to new line instead as because of word wrapping it was still confusing even when set at buffer width, so now it will only visually wrap and you have to wrap to new line by yourself, I think that is the most intuitive approach for chat window
