### ISSUE TITLE
german umlauts - broken format

### ISSUE THREAD

**Issue by bukenbp8** [CopilotC-Nvim/CopilotChat.nvim#30]
Hi I have following problem with using the chat with german umlauts (e.g. ä, ö, ü)

Example prompt: generate me a sentence with a lot of german umlauts.

NVIM v0.9.5 
Distro is Arch Linux

Screenshot: 
![screenshot-20240208-103053](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/59826445/03d4c286-307f-4f03-b2c2-07e1d9adfe85)

The issue is that sometimes they are replaced like ü with <c3> and sometimes they are displayed but the following character is placed in a completely different position. 

I use Lazyvim but i tried also with Astronvim both with the same problem.

**Comment by bukenbp8** [comment]
Thank you for your fast reply! I switched the branch to pr-chinese-fix but i encountered this error whenever i want to prompt something: 

`Encountered SyntaxError loading plugin at /home/foo/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/copilot-plugin.py: unterminated string literal (detected at line 206) (chat_handler.py, line 206)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pynvim/plugin/host.py", line 187, in _load
    module = _handle_import(directory, name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynvim/plugin/host.py", line 40, in _handle_import
    return importlib.import_module(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "/home/foo/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/handlers/chat_handler.py", line 206
    f"Please visit {req['verification_uri']
    ^
SyntaxError: unterminated string literal (detected at line 206)`

i am not very familiar with python i guess its the string interpolation? Don't know if i have to delete something? Sorry to bother you with this. I really appreciate your work

**Comment by gptlang** [comment]
Sorry about that. Fixed it. Something weird with my LSP formatter

**Comment by bukenbp8** [comment]
Thank you very much! Its a bit slow but usable. Looking forward to see this in the main branch.

**Comment by gptlang** [comment]
It has now been fully fixed in main without the slowness
