### ISSUE TITLE
Expose the default mappings

### ISSUE THREAD

**Issue by DRKolev-code** [CopilotC-Nvim/CopilotChat.nvim#310]
I would like to separate the keymaps from the options (using lazy.nvim). Is it possible to expose all functions in the default keymaps the same way `close` and `reset` are?

**Comment by deathbeam** [comment]
The keymaps are for the copilot chat buffer so using lazy.nvim for them do not makes sense in first place tho, you cant lazy load on them and they are not global bindings either.

**Comment by DRKolev-code** [comment]
I understand. I was thinking of being able to execute those commands outside of the CopilotCat buffer. For example `show_diff` (`accept_diff`, `yank_diff`, ...) still acts on the CopilotChat buffer but I don't have to switch to that window to run the command. The same way that `reset` works now.
