### ISSUE TITLE
README improvement: `opts = {}` key must be specified for lazy.nvim installation

### ISSUE THREAD

**Issue by oryband** [CopilotC-Nvim/CopilotChat.nvim#341]
The following configuration doesn't work without at least adding a minimal, empty `opts = {}` section. Please add to readme.

```lua
  {
    "CopilotC-Nvim/CopilotChat.nvim",
    branch = "canary",
    dependencies = {
      { "zbirenbaum/copilot.lua" },
      { "nvim-lua/plenary.nvim" },
    },
    -- opts = {},  -- doesn't load or start plugin without this uncommented
  },
```

**Comment by deathbeam** [comment]
Interesting, so it doesnt load or does it crash on something?

**Comment by oryband** [comment]
I don't see any errors, the `:CopilotChat` commands just aren't availalb.e How can I check this? Note I'm using AstroNvim v4 https://astronvim.com/

**Comment by deathbeam** [comment]
> I don't see any errors, the `:CopilotChat` commands just aren't available. How can I check this? Note I'm using AstroNvim v4 https://astronvim.com/

If you dont see any errors then its probs not some weird crash related to that. But otherwise not rly familiar with astronvim either, but I would assume the errors would just be in :messages if any.

**Comment by folke** [comment]
The readme does mention the `opts = {}` no?

**Comment by deathbeam** [comment]
Alright so its intended behaviour then, was mostly worried that its on the plugin side in some way. And yea we even mention the opts, completely forgot :d

**Comment by oryband** [comment]
I understand the reason, it was just unclear to me that it has to be added. I wanted to use the default opts so i just removed this key entirely - which practically disabled the plugin and was unintuitive. I spent 30m figuring this out!
