### ISSUE TITLE
FEAT: Add possibility to use OpenAI gpt models instead of specifically github copilot

### ISSUE THREAD

**Issue by dqnk** [CopilotC-Nvim/CopilotChat.nvim#342]
I really like this plugin and the way it works and I would like to be able to use the OpenAI API instead of the Github copilot, while keeping most of the user experience the same. Reasons for this are cheaper prices with the API and faster models (gpt-4o is only available on the API, Github copilot does not support it yet).

I have researched the structure of the current project a little and the feature to me seems possible to implement (you would just have to send the curl to OpenAI instead of Github API). Would you be fine having this feature added to the plugin? Or should I fork it and make a separate plugin (I want to keep most of the UI). Would it be a licensing issue if I did this?

**Comment by gptlang** [comment]
Discussed here: https://github.com/CopilotC-Nvim/CopilotChat.nvim/discussions/286
