### ISSUE TITLE
Question: is `set cursorline` mandatory?

### ISSUE THREAD

**Issue by kjuq** [CopilotC-Nvim/CopilotChat.nvim#354]
In the status quo, `cursorline` is set when the `copilot-chat` buffer opens. However I'm curious whether it is a necessary behavior to make this plugin works properly. In my case, I prefer no `cursorline` because it is a bit annoying to focus coding.

If it weren't a mandatory option. I made a PR to add an option to disable that. So I will be so happy for you to review that.

Edit:
Sent PR (https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/355)

**Comment by deathbeam** [comment]
https://github.com/CopilotC-Nvim/CopilotChat.nvim?tab=readme-ov-file#customizing-buffers see

**Comment by kjuq** [comment]
I misunderstood the problem. I opened a new issue (#356).
