### ISSUE TITLE
Full-Context awareness in a Git repository or Folder

### ISSUE THREAD

**Issue by Hexdigest123** [CopilotC-Nvim/CopilotChat.nvim#360]
Hi, I wanted to ask if there's a plan for implementing full-context awareness in Git repositories or in general, projects opened in Neovim. Currently, I only find the option to choose between a single buffer or multiple buffers. If this is not currently possible, is it possible to customize the context for Copilot?

**Comment by jondkinney** [comment]
I would also love this! 🙌

**Comment by jellydn** [comment]
FYI - You might want to look to this discussion https://discord.com/channels/1200633211236122665/1209115196702859294/1261373682542968842

TLDR: not yet.

**Comment by tmillr** [comment]
I dont event get my whole project...only a few buffers max as context.

**Comment by deathbeam** [comment]
https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/495

For now this was added, that should help AI to at least figure out structure of the project

**Comment by deathbeam** [comment]
> I dont event get my whole project/dir (or rather, not even "all open buffers" as documented) as context when using `@buffers`...only 2 or 3 of my open buffers max. Is this the norm, or am I doing something wrong? How much context do you guys get? It wouldn't be a big deal if context was limited, but 2-3 random buffers is nothing.

Also very late reply, but we use github embeddings queries to determine if something should be included in context or not. and this is based on your prompt query so sometimes it can just ditch less relevant files. Also it depends on maximum token limit, but for example claude can handle a lot of data.

**Comment by deathbeam** [comment]
Ok this is now mostly implemented with `files:full` context, feel free to try :) There is no caching atm so it only works well for small to mid sized repositories, but its usable. For rest see #628
