### ISSUE TITLE
Please add a command to clear the highlights produced by :CopilotChatReview

### ISSUE THREAD

**Issue by Tebro** [CopilotC-Nvim/CopilotChat.nvim#362]
When using :CopilotChatReview it will print its suggestions in chat, but also highlight them in the buffer. Would be nice to be able to clear this highlights.

**Comment by masakiq** [comment]
This is a workaround.

By defining the following Lua function, you can clear the review highlights:

```lua
function CopilotChatReviewClear()
  local ns = vim.api.nvim_create_namespace('copilot_review')
  vim.diagnostic.reset(ns)
end

vim.api.nvim_create_user_command(
  'CopilotChatReviewClear',
  CopilotChatReviewClear,
  {}
)
```

Then, run the command:

```vim
:CopilotChatReviewClear
```

Alternatively, if you don't need the highlights, you might also consider using the keymap below to silence the function callbacks:

```lua
require("CopilotChat").setup {
  prompts = {
    Review = {
      callback = function(_, _)
        -- do nothing
      end,
    },
  },
end
```

**Comment by deathbeam** [comment]
Went with slightly different approach where it clears existing diagnostics on every new question.
