### ISSUE TITLE
Diff yank with 'gy' (the default mapping) doesn't work.

### ISSUE THREAD

**Issue by marwan-tanager** [CopilotC-Nvim/CopilotChat.nvim#364]
Hi, I couldn't get the `gy` mapping to yank the diff in the chat window to work. Also, it doesn't work if I assign any other key combination to `mappings.yank_diff`.

**Comment by sjonpaulbrown-cc** [comment]
I was experiencing the same issue. I had my clipboard set to `vim.o.clipboard = 'unnamedplus'`. When commenting this out, I was able to successfully use the `gy` mapping. 

The `gy` mapping stores the diff to the `"` register. You can validate that the diff is properly getting copied by running the `:registers "` command. After copying with `gy`, you need to validate the contents of the `"` register. If it is empty, you may be overwriting the register in some way.

**Comment by deathbeam** [comment]
Looks like this is resolved by register being configurable and original issue was mostly misunderstanding registers anyway I would say
