### ISSUE TITLE
feat: gpt-4o support

### ISSUE THREAD

**Issue by hrez** [CopilotC-Nvim/CopilotChat.nvim#366]
Hi,
copilot chat now supports gpt-4o. Could you add its support? - I think it would need to use https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken

Thanks.

**Comment by acheong08** [comment]
Thanks for notifying. I'll have a look

**Comment by acheong08** [comment]
> [GitHub Copilot Enterprise features on GitHub.com](https://docs.github.com/en/enterprise-cloud@latest/copilot/github-copilot-enterprise/github-copilot-enterprise-feature-set) and [Copilot Chat in GitHub Mobile](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/asking-github-copilot-questions-in-github-mobile) are now powered by the latest model from OpenAI, GPT-4o.

https://github.blog/changelog/2024-07-05-github-copilot-enterprise-on-gpt-4o/

It is not yet available for personal plans

**Comment by gptlang** [comment]
gpt-4o isn't available for personal plans afaik. Are you sure it works in vscode? I'll need to install vscode again

**Comment by gptlang** [comment]
```json
{
    "data": [
        {
            "capabilities": {
                "family": "gpt-3.5-turbo",
                "limits": {
                    "max_prompt_tokens": 7168
                },
                "object": "model_capabilities",
                "type": "chat"
            },
            "id": "gpt-3.5-turbo",
            "name": "GPT 3.5 Turbo",
            "object": "model",
            "version": "gpt-3.5-turbo-0613"
        },
        {
            "capabilities": {
                "family": "gpt-3.5-turbo",
                "limits": {
                    "max_prompt_tokens": 7168
                },
                "object": "model_capabilities",
                "type": "chat"
            },
            "id": "gpt-3.5-turbo-0613",
            "name": "GPT 3.5 Turbo (2023-06-13)",
            "object": "model",
            "version": "gpt-3.5-turbo-0613"
        },
        {
            "capabilities": {
                "family": "gpt-4",
                "limits": {
                    "max_prompt_tokens": 6144
                },
                "object": "model_capabilities",
                "type": "chat"
            },
            "id": "gpt-4",
            "name": "GPT 4",
            "object": "model",
            "version": "gpt-4-0613"
        },
        {
            "capabilities": {
                "family": "gpt-4",
                "limits": {
                    "max_prompt_tokens": 6144
                },
                "object": "model_capabilities",
                "type": "chat"
            },
            "id": "gpt-4-0613",
            "name": "GPT 4 (2023-06-13)",
            "object": "model",
            "version": "gpt-4-0613"
        },
        {
            "capabilities": {
                "family": "gpt-4-turbo",
                "limits": {
                    "max_prompt_tokens": 6144
                },
                "object": "model_capabilities",
                "type": "chat"
            },
            "id": "gpt-4-0125-preview",
            "name": "GPT 4 Turbo (2024-01-25 Preview)",
            "object": "model",
            "version": "gpt-4-0125-preview"
        },
        {
            "capabilities": {
                "family": "text-embedding-ada-002",
                "limits": {
                    "max_inputs": 256
                },
                "object": "model_capabilities",
                "type": "embeddings"
            },
            "id": "text-embedding-ada-002",
            "name": "Embedding V2 Ada",
            "object": "model",
            "version": "text-embedding-ada-002"
        },
        {
            "capabilities": {
                "family": "text-embedding-ada-002",
                "object": "model_capabilities",
                "type": "embeddings"
            },
            "id": "text-embedding-ada-002-index",
            "name": "Embedding V2 Ada (Index)",
            "object": "model",
            "version": "text-embedding-ada-002"
        },
        {
            "capabilities": {
                "family": "text-embedding-3-small",
                "object": "model_capabilities",
                "type": "embeddings"
            },
            "id": "text-embedding-3-small",
            "name": "Embedding V3 small",
            "object": "model",
            "version": "text-embedding-3-small"
        },
        {
            "capabilities": {
                "family": "text-embedding-3-small",
                "object": "model_capabilities",
                "type": "embeddings"
            },
            "id": "text-embedding-3-small-inference",
            "name": "Embedding V3 small (Inference)",
            "object": "model",
            "version": "text-embedding-3-small"
        }
    ],
    "object": "list"
}
```

CC @deathbeam 

Maybe we can have a `:CopilotChatModels` to fetch `https://api.githubcopilot.com/models` & display/select available models. Otherwise it's not obvious what model names are.

**Comment by gptlang** [comment]
btw we might want to set `gpt-4-0125`  as default since it's more recent and ranks higher on leaderboards rather than just `gpt-4` (alias for GPT 4 (2023-06-13))

**Comment by jellydn** [comment]
> Maybe we can have a :CopilotChatModels to fetch https://api.githubcopilot.com/models & 
display/select available models. Otherwise it's not obvious what model names are.

Nice idea @gptlang I like it 👏

**Comment by pidgeon777** [comment]
Hello everyone, maybe I missed some news, but I wanted to know if the `GPT-4o` model is also available for the **Personal** plan.

In case you are interested, I will forward this discussion I started:

https://github.com/orgs/community/discussions/123670

**Comment by pidgeon777** [comment]
> > Maybe we can have a :CopilotChatModels to fetch https://api.githubcopilot.com/models &
> > display/select available models. Otherwise it's not obvious what model names are.
> 
> Nice idea @gptlang I like it 👏

This is a great suggestion, maybe by using `vim.ui.select` or similar.

**Comment by gptlang** [comment]
I'm not very good at lua. I'm getting this error: ` E5560: Vimscript function must not be called in a lua loop callback `

Any clue how to fix this? @jellydn

**Comment by pidgeon777** [comment]
I've attempted to use this setting:

```model = "gpt-4-0125-preview"```

Has anyone else done the same? I read here that the model should contain information indexed up to **December 2023**, but when I ask questions like:

"What is the latest build of Python?"

"What is the latest build of the Linux Kernel?"

I respectively get the answers:

"Python 3.10.4"

"5.15"

This is peculiar because it seems that the model's knowledge actually stops around **March 2022**.

Have you noticed this as well? Could you conduct some tests?

**Comment by pidgeon777** [comment]
Some info about the model training data:

https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4

**Comment by gptlang** [comment]
AI is generally very unreliable.

![image](https://github.com/user-attachments/assets/2792b238-6350-4e47-9818-ca206d7cf380)

This was with a prompt change to say: "Knowledge Cutoff: December 2023".

![image](https://github.com/user-attachments/assets/04c03a0f-f25c-46d9-9771-66aaf088e6c7)

However, word it differently and you'll get correct more up to date info ([see here](https://www.python.org/downloads/release/python-3120/))

**Comment by pidgeon777** [comment]
I'm still having issues. I asked the questions using `:CopilotChat <Question>`:

![image](https://github.com/user-attachments/assets/81f78923-b100-48c3-8968-8b82baa5f75b)

For somewhat reason the "new" `gpt-4` model seems to not be active.

This is my setup:

```lua
{
    "CopilotC-Nvim/CopilotChat.nvim",
    branch = "canary",
    cmd = "CopilotChat",
    opts = function()
      local user = vim.env.USER or "User"
      user = user:sub(1, 1):upper() .. user:sub(2)
      return {
        model = "gpt-4-0125-preview",
        auto_insert_mode = true,
        show_help = true,
        question_header = "  " .. user .. " ",
        answer_header = "  Copilot ",
        window = {
          width = 0.4,
        },
        selection = function(source)
          local select = require("CopilotChat.select")
          return select.visual(source) or select.buffer(source)
        end,
      }
    end,
    keys = {
      { "<c-s>", "<CR>", ft = "copilot-chat", desc = "Submit Prompt", remap = true },
      { "<leader>a", "", desc = "+ai", mode = { "n", "v" } },
      {
        "<leader>aa",
        function()
          return require("CopilotChat").toggle()
        end,
        desc = "Toggle (CopilotChat)",
        mode = { "n", "v" },
      },
      {
        "<leader>ax",
        function()
          return require("CopilotChat").reset()
        end,
        desc = "Clear (CopilotChat)",
        mode = { "n", "v" },
      },
      {
        "<leader>aq",
        function()
          local input = vim.fn.input("Quick Chat: ")
          if input ~= "" then
            require("CopilotChat").ask(input)
          end
        end,
        desc = "Quick Chat (CopilotChat)",
        mode = { "n", "v" },
      },
      -- Show help actions with telescope
      { "<leader>ad", M.pick("help"), desc = "Diagnostic Help (CopilotChat)", mode = { "n", "v" } },
      -- Show prompts actions with telescope
      { "<leader>ap", M.pick("prompt"), desc = "Prompt Actions (CopilotChat)", mode = { "n", "v" } },
    },
    config = function(_, opts)
      local chat = require("CopilotChat")
      require("CopilotChat.integrations.cmp").setup()

      vim.api.nvim_create_autocmd("BufEnter", {
        pattern = "copilot-chat",
        callback = function()
          vim.opt_local.relativenumber = false
          vim.opt_local.number = false
        end,
      })

      chat.setup(opts)
    end,
  }
```

Am I doing something wrong?

**Comment by gptlang** [comment]
I added the following line to the system prompt:
```
Knowledge Cutoff: December 2024
```

Yes, I know it's not yet December. However, it fails to answer the question with `Knowledge Cutoff: December 2023`... I only just now realized my previous typo. Giving it a fake knowledge cutoff improves performance. Not sure if we should do that though

**Comment by pidgeon777** [comment]
![image](https://github.com/user-attachments/assets/12d4fc21-c1dc-489f-b77c-70f3fd4c3864)

```
  User ───

When was Python 3.12 released?

  Copilot ───

Python 3.12 was released on October 2, 2023.
```

You were correct. At this point, I assume it wasn't working initially because there was a history of another chat active.

However, aside from the knowledge of events, I wonder if giving it a manual knowledge cutoff (set to 2024) could also make it more "intelligent".

**Comment by gptlang** [comment]
> However, aside from the knowledge of events, I wonder if giving it a manual knowledge cutoff (set to 2024) could also make it more "intelligent".

CC @jellydn Do you think we should put in a "fake" knowledge cutoff?

**Comment by jellydn** [comment]
> Do you think we should put in a "fake" knowledge cutoff?

No, we shouldn't do that.

**Comment by thenbe** [comment]
> Hi, Thanks for the quick implementation. Does gpt-4o work for you? Because I get "model not supported". It works in vscode's latest chat plugin as far as I can tell. So I wonder if it needs headers tweaked or it's just my neovim setup.

@hrez I got that error too (`model not supported`). To fix it, I had to use the full model name instead of the alias. I'm not sure why the alias wasn't working.


```diff
opts = {
-	model = 'gpt-4o',
+	model = 'gpt-4o-2024-05-13',
}
```

You can find the latest model aliases here: https://platform.openai.com/docs/models/gpt-4o

**Comment by pidgeon777** [comment]
> > Hi, Thanks for the quick implementation. Does gpt-4o work for you? Because I get "model not supported". It works in vscode's latest chat plugin as far as I can tell. So I wonder if it needs headers tweaked or it's just my neovim setup.
> 
> @hrez I got that error too (`model not supported`). To fix it, I had to use the full model name instead of the alias. I'm not sure why the alias wasn't working.
> 
> 
> ```diff
> opts = {
> -	model = 'gpt-4o',
> +	model = 'gpt-4o-2024-05-13',
> }
> ```
> 
> You can find the latest model aliases here: https://platform.openai.com/docs/models/gpt-4o

But 4o is currently available for Enterprise GitHub Copilot subscribers, or also Personal plans?

**Comment by gptlang** [comment]
>  I'm not sure why the alias wasn't working.

- #378 

Since nobody is reviewing it and it works for me, I'll just be merging it
