### ISSUE TITLE
Pull request creation failed. Validation failed: must be a collaborator  

### ISSUE THREAD

**Issue by gptlang** [CopilotC-Nvim/CopilotChat.nvim#369]
![image](https://github.com/user-attachments/assets/54d673b5-24a1-4f02-9298-f5c8c947a442)

Well, I was using the wrong account but this happened. Is the repository somehow closed to outside collaborators?

**Comment by jellydn** [comment]
I guess something new from Github 
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/21d580f4-a516-4488-8bed-e490ea1e2e76">
Do we change any settings recently? @gptlang @deathbeam

**Comment by gptlang** [comment]
Looks like a change GitHub made such that random people can't open a PR with branches from a repository they don't own.
