### ISSUE TITLE
curl failed to verify the legitimacy of the server and therefore could not

### ISSUE THREAD

**Issue by Liugq5713** [CopilotC-Nvim/CopilotChat.nvim#375]
Failed to get response: {
  exit = 60,
  message = 'get https://api.github.com/copilot_internal/v2/token - curl error exit_code=60 stderr={ "curl: (60) SSL certificate problem: self signed certificate in certificate chain", "More details here: https://curl.se/docs/sslcerts.html", "", "curl failed to verify the legitimacy of the server and therefore could not", "establish a secure connection to it. To learn more about this situation and", "how to fix it, please visit the web page mentioned above." }',
  stderr = '{ "curl: (60) SSL certificate problem: self signed certificate in certificate chain", "More details here: https://curl.se/docs/sslcerts.html", "", "curl failed to verify the legitimacy of the server and therefore could not", "establish a secure connection to it. To learn more about this situation and", "how to fix it, please visit the web page mentioned above." }'
}

**Comment by Liugq5713** [comment]
i want to find a extension like mac-ca-vscode , but not found. 
https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot

**Comment by gptlang** [comment]
Are you using a proxy?

**Comment by gptlang** [comment]
Set `allow_insecure=true` in config

**Comment by minaketank** [comment]
Trying to install npm on my wsl (ubuntu-22.04). But getting the below issue:
command:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

Error:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
