### ISSUE TITLE
While installing npm on wsl (ubuntu-22.04), getting curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it

### ISSUE THREAD

**Issue by minaketank** [CopilotC-Nvim/CopilotChat.nvim#378]
Trying to install npm on my wsl (ubuntu-22.04). But getting the below issue:
command:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

Error:
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by minaketank** [comment]
solved it by adding --insecure

**Comment by minaketank** [comment]
But now while trying run below
nvm install 22

getting
Version '22' not found - try `nvm ls-remote` to browse available versions.

**Comment by gptlang** [comment]
Open a report with nvm. Not our problem
