### ISSUE TITLE
Seems that the Custom Prompts using a custom system_prompt is not actually changing the system prompt

### ISSUE THREAD

**Issue by GitMurf** [CopilotC-Nvim/CopilotChat.nvim#381]
The instructions here: https://github.com/CopilotC-Nvim/CopilotChat.nvim?tab=readme-ov-file#custom-system-prompts

show that you can add a custom system_prompt like this:

```lua
{
  system_prompt = 'Your name is Github Copilot and you are a AI assistant for developers.',
  prompts = {
    MyCustomPromptWithCustomSystemPrompt = {
      system_prompt = 'Your name is Johny Microsoft and you are not an AI assistant for developers.',
      prompt = 'Explain how it works.',
    },
  },
}
```

But when I try this with something obvious like the following:

```lua
{
    prompts = {
      MyCustomPiratePrompt = {
        system_prompt = [[You are fascinated by pirates, so please respond in pirate speak.]],
        prompt = 'what is a sorting algo?',
      },
    },
}
```

I get a regular response which appears to be using the main system prompt as the response is NOT in pirate speak. Here is the result:

![image](https://github.com/user-attachments/assets/75fc66b5-de33-468d-bb28-2949c89374c2)

If I override the default system prompt using the following in config:

```lua
{
    ...
    system_prompt = [[You are fascinated by pirates, so please respond in pirate speak.]],
    prompts = { ... },
    ...
}
```

Then I indeed get a response in "pirate speak" confirming the system_prompt works as defined. I would expect the same result for my custom prompt above where using that individual custom prompt would respond in pirate speak just for that specific prompt (and regular chat prompt would use the default system prompt still).

![image](https://github.com/user-attachments/assets/7188c6d7-77d6-4bb2-a691-4f9d68a66f05)

**Comment by GitMurf** [comment]
Also to confirm I turned on the debug flag so that I could see the prompt being used and it indeed is showing the default system prompt and not the custom one.

**Comment by gptlang** [comment]
GitHub not sending me email notifications for some reason. Will look into this

**Comment by gptlang** [comment]
Looks like a documentation issue. 

After defining custom prompts, you can use them by doing `:CopilotChat<whatever_you_named_the_prompt>`

**Comment by GitMurf** [comment]
@gptlang what do you mean? I did not have a problem executing my custom prompt (using "/MyCustomPrompt" in the message) and it correctly runs the prompt EXCEPT not if I try to override the "system" prompt with it. It just appears that the system prompt is not being customized. Does that make sense?

**Comment by gptlang** [comment]
Huh that's weird. It's definitely working on my end.

**Comment by gptlang** [comment]
Ah sorry, I didn't notice you were using `/<custom prompt>`. Was testing with `:CopilotChat<prompt>` format. Indeed reproducible.

**Comment by GitMurf** [comment]
@gptlang can you paste in example of your custom prompt config your are testing (with both prompt and system prompt customized) so I can try what you are testing? Thanks

**Comment by GitMurf** [comment]
> Ah sorry, I didn't notice you were using `/<custom prompt>`. Was testing with `:CopilotChat<prompt>` format. Indeed reproducible. 

Ohh so you mean it actually works with CopilotChatMyCustom but the issue appears to just be when using /MyCustom within the chat window message?

**Comment by gptlang** [comment]
Yup. I've found the faulty function. Fix in progress.

**Comment by GitMurf** [comment]
Sweet thanks a lot!

**Comment by gptlang** [comment]
![image](https://github.com/user-attachments/assets/54620d51-fa4b-44e9-b9d5-c839cc296031)

Ahar finally.

Looks like there is a bit of a mess in terms of behavior leftover from the Python days. There used to be some hacks around system vs user prompts where some built in ones used recursive `/` prompting. Not sure if that's optimal but I won't break it for now.

**Comment by gptlang** [comment]
@jellydn @deathbeam 

https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/4b9ca95bbc737a94e8be582716a04e827911b9b6/README.md?plain=1#L344-L358

We don't have any `USER_` prompts & it feels better to have [prompts.lua](https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/canary/lua/CopilotChat/prompts.lua) as part of the default `prompts` config instead. We can then get rid of the weird string magic with search/replace thing. Would this break anything?

**Comment by jellydn** [comment]
> USER_

Let's keep it. As I recall, we have `USER_PROMPT` to allow user to change or insert part of the prompt to our system/copilot prompts before call API (curl). Correct me if we have changed this logic? @deathbeam

**Comment by acheong08** [comment]
@jellydn 

```lua
CustomUserPrompt = {
        prompt = 'what is a sorting algo?',
      },
```

this should default to normal system prompt
