### ISSUE TITLE
[Request] Implement Copilot Chat GPT4-o

### ISSUE THREAD

**Issue by und3fined** [CopilotC-Nvim/CopilotChat.nvim#383]
Now Copilot Chat support GPT-4o. (https://github.blog/changelog/2024-07-31-github-copilot-chat-and-pull-request-summaries-are-now-powered-by-gpt-4o/)

The team can implement it?

**Comment by gptlang** [comment]
https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/2c4d2954f9b56945dc8d053903b16759d08f9f37

Was done a few days ago
