### ISSUE TITLE
Invalid instruction for new user

### ISSUE THREAD

**Issue by jdhao** [CopilotC-Nvim/CopilotChat.nvim#392]
When I run the command `CopilotChat` for the first time, I see the warning message in here: https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/bddda2aaf66d34bf6dbae8af26166187a4343cca/lua/CopilotChat/copilot.lua#L290

With the latest version of plugin `zbirenbaum/copilot.lua`, the command to run is actually `Copilot auth` IMO.

**Comment by jellydn** [comment]
Thanks for your report. You're right. That's instruction for copilot.vim

```
Start Vim/Neovim and invoke `:Copilot setup`.
```
