### ISSUE TITLE
CI failing: Error: Failed to install Lua: Error: Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by gptlang** [CopilotC-Nvim/CopilotChat.nvim#393]
>    luaVersion: "luajit-2.1.0-beta3"

We probably shouldn't be testing with beta versions?

**Comment by jellydn** [comment]
Agree. Let's remove that then.

**Comment by jellydn** [comment]
Just FYI https://github.com/leafo/gh-actions-lua/issues/49
