### ISSUE TITLE
Cannot change layout during runtime

### ISSUE THREAD

**Issue by RomaLzhih** [CopilotC-Nvim/CopilotChat.nvim#406]
Hi developers! 

It seems that once we finish the window layout configuration, there is no way to change it after the nvim starts. For example, if I set the window layout to be 'vertical', I cannot create a new chat window in 'replace' after the nvim starts.

I suggest adding one API that allows the user to choose the layout they want during runtime, like most terminal plugins.

If there is already a solution for this feature, please let me know. Thanks.

**Comment by teocns** [comment]
Doesn't vim-native keystrokes like `<C-w> + H / J / K / L` work for you to move the window around?

**Comment by RomaLzhih** [comment]
Sure, it works and eases the pain a little bit. 
But what if I want to create a new full-screen chat buffer, like the `replace` provided in the window layout configuration?

**Comment by deathbeam** [comment]
There already is api for this, e.g something like this should work:

```lua
    chat.toggle({
        window = {
            layout = 'horizontal'
        }
    })
```

but it doesnt atm, e.g this is a bug

**Comment by deathbeam** [comment]
Nvm my testing method was incorrect, this actually works fine
