### ISSUE TITLE
Freezing neovim and takes 100% of CPU

### ISSUE THREAD

**Issue by Mofiqul** [CopilotC-Nvim/CopilotChat.nvim#41]
`:CopilotChatVisial` freezing Neovim and uses 100% of CPU. This does not happen every time but very frequent. And if it happens, there is no other way than killing Neovim process.

**Comment by jellydn** [comment]
Hi @Mofiqul Thanks for your report. Could you share your Python and Neovim version? I've got the similar issue with Neovim nightly sometime recently.

cc @gptlang @ziontee113

**Comment by Mofiqul** [comment]
@jellydn 
**Neovim**
```
NVIM v0.10.0-dev+2324-g4948fa42e
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
```
**Python**
```
Python 3.12.1
```

**Comment by jellydn** [comment]
> Is there any log file or something I can check?

You could enable this flag @Mofiqul 
```lua
      debug = false, -- Enable or disable debug mode, the log file will be in ~/.local/state/nvim/CopilotChat.nvim.log
```

**Comment by jellydn** [comment]
Hi @Mofiqul Is this still happening on your PC?

**Comment by pesho65** [comment]
I have the same issue. Even when I am using CopilotChat not the visual my neovim freezes.

**Comment by jellydn** [comment]
Thanks @pesho65 for your confirmation. Is that still happening with you? I've added more logging on this commit https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/003d7cc3357d0d9aa008cdbd7caf6b9802ced238 

I am trying to reproduce this on my side but it's been working well for me recently.

**Comment by Mofiqul** [comment]
@jellydn - It's been working fine at my machine as well since last couple of days
