### ISSUE TITLE
Expected value but found invalid token at character 1

### ISSUE THREAD

**Issue by gammons** [CopilotC-Nvim/CopilotChat.nvim#415]
Hi there, I am trying to use CopilotChat.nvim.  I think maybe the main difference is I am using packer.nvim as my package manager.  I am installing Copilot chat like so:

```lua
  use {
    'CopilotC-Nvim/CopilotChat.nvim',
    branch = 'canary',
    requires = {
      'github/copilot.vim',
      'nvim-lua/plenary.nvim',
    }
  }

-- copilot chat
require("CopilotChat").setup({
   debug = true,
})
```

Then I run `PackerSync` and it looks like CopilotChat is installed correctly.  (PackerSync is also making sure that all other libraries / dependencies are up-to-date as well)

Here is the output of `checkhealth CopilotChat`:

```
CopilotChat: require("CopilotChat.health").check()

CopilotChat.nvim [core] ~
- OK nvim: NVIM v0.10.1
  Build type: Release
  LuaJIT 2.1.1725453128
  Run ":verbose version" for more info

CopilotChat.nvim [commands] ~
- OK curl: curl 8.9.1 (x86_64-pc-linux-gnu) libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.63.0 nghttp3/1.5.0
  Release-Date: 2024-07-31
  Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
  Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
- OK git: git version 2.46.0

CopilotChat.nvim [dependencies] ~
- OK plenary: installed
- OK copilot: copilot.vim
- WARNING tiktoken_core: missing, optional for token counting. See README for installation instructions.
- OK treesitter[markdown]: installed
- OK treesitter[diff]: installed
```

However, if I try to enter a prompt into the window, or if I run `CopilotChatExplain`, I am getting the following error:

`[CopilotChat.nvim] "Expected value but found invalid token at character 1`

Any help to debug would be greatly appreciated.  Thanks!

**Comment by deathbeam** [comment]
I improved the error logging so can you check again now and check the error? @thomastthai @gammons

**Comment by gammons** [comment]
@thomastthai FWIW I was getting that error as well.  For me it was happening because I had `luajit-tiktoken-bin` installed (I'm using Arch linux).  When I removed that library, copilot chat worked for me.

**Comment by gammons** [comment]
going to close this issue since this seems to be fixed for me.

**Comment by gammons** [comment]
@thomastthai I would have thought that as well, but it was disabled for my work org, which is the org that's paying for copilot.  The weird thing is that regular copilot autocomplete was working just fine with that IDE option disabled :shrug:
