### ISSUE TITLE
CopilotChatCommitStaged fails with error `prompt token limit exceeded`

### ISSUE THREAD

**Issue by bashtoni** [CopilotC-Nvim/CopilotChat.nvim#417]
When trying to get Copilot to write a commit message for me with `:CopilotChatCommitStaged` I get the following error returned:

```
Failed to get response: {"error":{"message":"prompt token limit exceeded","param":"","code":"","type":""}}
```

This definitely worked previously - seems to have broken in the last week or two?

**Comment by deathbeam** [comment]
Thats very odd git behaviour, i guess while `git commit` message is open it creates bunch of temporary files in .git directory. Created PR with fix that should resolve this, thanks for debugging it @masakiq
