### ISSUE TITLE
Nvim crushes whenever ran 

### ISSUE THREAD

**Issue by MuntasirSZN** [CopilotC-Nvim/CopilotChat.nvim#423]
This is the output, and yes, its your plugin, removing your plugin makes nvim work as usual.

```
thread '<unnamed>' panicked at src/lib.rs:227:70:
called `Result::unwrap()` on an `Err` value: InvalidPadding
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    31877 IOT instruction (core dumped)  nvim . > list.txt
```

Pls solve it. I am running somehow without plugin.

**Comment by gptlang** [comment]
This is weird. Looks like tokens aren't proper base64. Did something get corrupted during download? Try `rm -rf .cache/nvim/*.tiktoken`

**Comment by MuntasirSZN** [comment]
> This is weird. Looks like tokens aren't proper base64. Did something get corrupted during download? Try `rm -rf .cache/nvim/*.tiktoken`

Doing this works.
