### ISSUE TITLE
where can i find logs 

### ISSUE THREAD

**Issue by samarth-nagar** [CopilotC-Nvim/CopilotChat.nvim#424]
I am not sure if this is even an feature or not I just to have an history of all things I have talked to copilot about somewhere

**Comment by deathbeam** [comment]
You can do :CopilotChatSave <name>/:CopilotChatLoad <name> to store chats but thats about it. There is some stuff that is logged but not much if you dont have debug enabled, you can see where logs are stored via :CopilotChatDebugInfo

**Comment by samarth-nagar** [comment]
oh thanks!,
Is there an way to have that turned on that by default so it stores everything even if someone forget to save
