### ISSUE TITLE
Observing "CopilotChat/prompts.lua:38: attempt to index a nil value (field 'loop')"

### ISSUE THREAD

**Issue by pradeepprakash** [CopilotC-Nvim/CopilotChat.nvim#425]
Observing "CopilotChat/prompts.lua:38: attempt to index a nil value (field 'loop')",  **when trying to integrate and launch CopilotChat** with vim with lua enabled

**VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Oct  4 2024 11:00:58)**
.
Huge version without GUI.
.
.
+cursorbind        **+lua**               +scrollbind        +wildmenu

Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-E -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lrt -ldl -L$HOME/.local/lib -llua -Wl,-E -fstack-protector -L/usr/local/lib -L/volume/hab/Linux/Ubuntu-20.04/x86_64/perl/5.14.4-20140626/lib/5.14.4/x86_64-linux/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lc -L/volume/hab/Linux/Ubuntu-20.04/x86_64/python3/3.10.2/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -lpthread -ldl -lutil -lm -lm -lruby-2.7 -lm -L/usr/lib

**Edit:**
Note: Was able to integrate the [ https://github.com/github/copilot.vim ] sucessfully and use it.

**Comment by deathbeam** [comment]
CopilotChat.nvim is https://github.com/neovim/neovim plugin not vim plugin. For differences and possible migration see here: https://neovim.io/doc/user/nvim.html#nvim-from-vim
