### ISSUE TITLE
see ':CopilotChatModels' for available models

### ISSUE THREAD

**Issue by Vinni-Cedraz** [CopilotC-Nvim/CopilotChat.nvim#451]
There isn't any `:CopilotChatModels` command available.

![image](https://github.com/user-attachments/assets/482b08a7-59a4-4e61-874c-0b3ef44c1d5d)

**Comment by deathbeam** [comment]
![image](https://github.com/user-attachments/assets/2386fa56-2fc1-4649-a75c-8c3a7eb7133f)

do you have up to date plugin version? because there is

**Comment by Vinni-Cedraz** [comment]
> do you have up to date plugin version? because there is

Yes it is updated, but I found out the problem and I think it might be an issue...

I used the default install available on readme, but with lazy loading:

return {
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		branch = "canary",
		dependencies = {
			{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
			{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
		},
		opts = {
			debug = true, -- Enable debugging
			model = 'gpt-4', -- 'gpt-3.5-turbo' or 'gpt-4'
			temperature = 0.1,
		},
		lazy = true,
		cmd = "CopilotChatToggle",
	}
}

Once I removed the lazy loading, the other commands started to work:

return {
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		branch = "canary",
		dependencies = {
			{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
			{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
		},
		opts = {
			debug = true, -- Enable debugging
			model = 'gpt-4', -- 'gpt-3.5-turbo' or 'gpt-4'
			temperature = 0.1,
		},
}

There might be an issue with CopilotC-Nvim's compatibility with lazy loading, "cmd" was not supposed to restrict the commands of the plugin, but to be the entry-point, the command that loads the plugin.

**Comment by Vinni-Cedraz** [comment]
> do you have up to date plugin version? because there is

Yes it is updated, but I found out the problem and I think it might be an issue...

I used the default install available on readme, but with lazy loading:

return {
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		branch = "canary",
		dependencies = {
			{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
			{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
		},
		opts = {
			debug = true, -- Enable debugging
			model = 'gpt-4', -- 'gpt-3.5-turbo' or 'gpt-4'
			temperature = 0.1,
		},
		lazy = true,
		cmd = "CopilotChatToggle",
	}
}

Once I removed the lazy loading, the other commands started to work:

return {
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		branch = "canary",
		dependencies = {
			{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
			{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
		},
		opts = {
			debug = true, -- Enable debugging
			model = 'gpt-4', -- 'gpt-3.5-turbo' or 'gpt-4'
			temperature = 0.1,
		},
}

There might be an issue with CopilotC-Nvim's compatibility with lazy loading, "cmd" was not supposed to restrict the commands of the plugin, but to be the entry-point, the command that loads the plugin.

**Comment by Vinni-Cedraz** [comment]
> do you have up to date plugin version? because there is

Yes it is updated, but I found out the problem and I think it might be an issue...

I used the default install available on readme, but with lazy loading:

return {
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		branch = "canary",
		dependencies = {
			{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
			{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
		},
		opts = {
			debug = true, -- Enable debugging
			model = 'gpt-4', -- 'gpt-3.5-turbo' or 'gpt-4'
			temperature = 0.1,
		},
		lazy = true,
		cmd = "CopilotChatToggle",
	}
}

Once I removed the lazy loading, the other commands started to work:

return {
	{
		"CopilotC-Nvim/CopilotChat.nvim",
		branch = "canary",
		dependencies = {
			{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
			{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
		},
		opts = {
			debug = true, -- Enable debugging
			model = 'gpt-4', -- 'gpt-3.5-turbo' or 'gpt-4'
			temperature = 0.1,
		},
}

There might be an issue with CopilotC-Nvim's compatibility with lazy loading, "cmd" was not supposed to restrict the commands of the plugin, but to be the entry-point, the command that loads the plugin.

**Comment by deathbeam** [comment]
Well im not sure how lazy.nvim works but if you used CopilotChatToggle and the plugin did not loaded then it looks like either configuration issue or lazy.nvim issue. The commands are set up when plugin loads so if you do load the plugin they simply wont be there by default.

**Comment by Vinni-Cedraz** [comment]
The plugin loads with CopilotChatToggle, but the other commands of the plugin are not available. Only :CopilotChatToggle is.

Yes, it's probably a lazy.nvim issue, sorry. I just removed lazy loading for now and your plugin is working with all commands now.
