### ISSUE TITLE
claude 3.5 sonnet is already available on Copilot

### ISSUE THREAD

**Issue by Vinni-Cedraz** [CopilotC-Nvim/CopilotChat.nvim#452]
VS Code users can already chose it as a model on Copilot Chat.

https://github.blog/changelog/2024-11-01-claude-3-5-sonnet-is-now-available-to-all-copilot-users-in-public-preview/

How can we make it available here as well?

**Comment by deathbeam** [comment]
Its already implemented, update your plugin version
![image](https://github.com/user-attachments/assets/d71ace05-5824-40b7-b0bb-9cfbddc2e2d8)

**Comment by deathbeam** [comment]
Also make sure you are on `canary` branch as per README
