### ISSUE TITLE
Update system prompt to be model agnostic

### ISSUE THREAD

**Issue by AeronCyther** [CopilotC-Nvim/CopilotChat.nvim#453]
Now that we have the capability to select a model of our choice, shouldn't the system prompt either mention the selected model name or not specify a model name at all?

https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/12ac3974daea98cd41e7d483bdb11cc8b6305623/lua/CopilotChat/prompts.lua#L26

**Comment by deathbeam** [comment]
Thats true, its not necessary anymore and I think we can live with some hallucinations when asking the AI about its model type, so probs should be removed completely. I will make a pr
