### ISSUE TITLE
Option to disable info logs

### ISSUE THREAD

**Issue by 0xayko** [CopilotC-Nvim/CopilotChat.nvim#461]
Unless I'm missing something there is currently no way to disable the plenary info logs like "Claude enabled" or "saved chat history" which are especially annoying with cmdheight 0 because it's all hit-enter prompts

**Comment by deathbeam** [comment]
We probs just need something like logging: INFO|DEBUG|TRACE|ERROR and then just pass that to our logger and done, i can look at this tomorrow if noone else wants to pick it up
