### ISSUE TITLE
Copilot Extentions agent Support

### ISSUE THREAD

**Issue by biosugar0** [CopilotC-Nvim/CopilotChat.nvim#466]
GitHub recently introduced Copilot Extensions:
https://docs.github.com/en/copilot/building-copilot-extensions/about-building-copilot-extensions

For instance, if a user enables the [Perplexity AI extension](https://github.com/marketplace/perplexityai), they can send requests to the Perplexity API directly from Copilot.

It would be extremely useful if CopilotChat.nvim could support calling these agents as well. In VS Code, this can be done by using the `@` prefix, such as `@perplexityai`.
<img width="533" alt="Screenshot 2024-11-05 10:23:23" src="https://github.com/user-attachments/assets/b96cc176-7f00-4aac-a619-5b8bb3483c5c">

In my testing with Neovim, I found that Perplexity can be called with the Copilot token by implementing this approach:
https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/465
<img width="1893" alt="Screenshot 2024-11-10 14:56:48" src="https://github.com/user-attachments/assets/18c5c880-a0dd-4a2c-8596-7f22fb9f8a36">

In the case of Perplexity, responses include content.copilot_references, so displaying referenced URLs and titles could enhance the user experience. I believe this addition would integrate seamlessly with the current implementation and add significant convenience!

In addition, sending a GET request to `https://api.githubcopilot.com/agents` retrieves a list of agents available to the user.

**Comment by deathbeam** [comment]
Thanks for your initial PR @biosugar0, was super helpful. Created PR that implements this feature, together with @agent (and changed @buffer to #buffer etc).

Also added reference listing too:

![image](https://github.com/user-attachments/assets/1d3e6b82-73c1-42df-8a66-73b1cfe3f89d)

**Comment by benelan** [comment]
Never mind, it wasn't actually working in the VSCode extension. I think I need to have an org admin enable access, sorry for the false alarm

**Comment by biosugar0** [comment]
@deathbeam Thank you for adding such a convenient feature! 

It would be even more useful if we could configure settings for each agent individually. For example, Perplexity AI allows you to use models like those described here:  
https://docs.perplexity.ai/guides/model-cards

It might be helpful to have a configuration like the example below:  
```
local opts = {
  debug = false,
  model = 'claude-3.5-sonnet', -- default model
  agents = { -- agent-specific configurations
    perplexityai = {
      model = 'llama-3.1-sonar-huge-128k-online', -- agent-specific model
    },
  },
  prompts = prompts,
}
local chat = require('CopilotChat')
chat.setup(opts)
```

**Comment by deathbeam** [comment]
oh interesting, did not knew theres extra options per agent. maybe its worth opening new issue for that? 

> @deathbeam Thank you for adding such a convenient feature!
> 
> It would be even more useful if we could configure settings for each agent individually. For example, Perplexity AI allows you to use models like those described here: https://docs.perplexity.ai/guides/model-cards
> 
> It might be helpful to have a configuration like the example below:
> 
> ```
> local opts = {
>   debug = false,
>   model = 'claude-3.5-sonnet', -- default model
>   agents = { -- agent-specific configurations
>     perplexityai = {
>       model = 'llama-3.1-sonar-huge-128k-online', -- agent-specific model
>     },
>   },
>   prompts = prompts,
> }
> local chat = require('CopilotChat')
> chat.setup(opts)
> ```

**Comment by biosugar0** [comment]
I created a new issue for this topic: https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/526
