### ISSUE TITLE
Unexpected Exclusion of CJK Character Set

### ISSUE THREAD

**Issue by nyanyacoffee** [CopilotC-Nvim/CopilotChat.nvim#469]
The recent commit ec9c848 which "Automatically sanitize input sent to copilot API" appears to have unintentionally removed non-English characters (CJK languages).

### Problem
- Sending messages with Chinese/Japanese/Korean characters now fails
- API returns the error: "message content must not be empty"
- Non-English text is completely stripped out

**Comment by deathbeam** [comment]
Hmm, I tried to avoid this and only strip emojis and stuff but I guess i stripped more than i wanted. I will try to look at this today.

**Comment by deathbeam** [comment]
Decided to revert the change, its probably better to just let github handle it upstream or properly debug this
