### ISSUE TITLE
Highlighting a line of code is no longer possible

### ISSUE THREAD

**Issue by SpaghettiC0des** [CopilotC-Nvim/CopilotChat.nvim#552]
With the recent updates, when I want to highlight a line of code and run `:CopilotChatExplain`, it will highlight the whole code when the window for copilot chat opens. 

### Example
<img width="929" alt="Screenshot 2024-11-20 at 16 02 13" src="https://github.com/user-attachments/assets/488c8401-448d-42e7-be92-482874d63862">

I highlighted `line 11` and then ran the explain command; it will highlight everything when the chat window response opens.

**Comment by deathbeam** [comment]
Yea the default selection was changed from visual || line to visual || buffer. You can change it back by doing this:

```
  selection = function(source)
    local select = require('CopilotChat.select')
    return select.visual(source) or select.line(source)
  end,
```

On that note looks like visual selection for current line isnt working straight up so I need to fix that first :d

**Comment by deathbeam** [comment]
Ok should work now :)
