### ISSUE TITLE
Claude 3.5 Sonnet model not showing up in Windows

### ISSUE THREAD

**Issue by ke-a** [CopilotC-Nvim/CopilotChat.nvim#557]
I'm using LazyVim on Windows with Copilotchat.nvim installed through extras. When I run :CopilotChatModels, I noticed that Claude 3.5 Sonnet is not available in the model list. I've made sure Claude is enabled in my GitHub Copilot account settings. I tested the same setup (latest versions of both LazyVim and Copilotchat.nvim) in GitHub Codespaces and the model shows up there. Is this a Windows-specific issue?

![image](https://github.com/user-attachments/assets/ed8c7866-5a62-4bb2-8fb4-f71bfd3c0560)

**Comment by ke-a** [comment]
![image](https://github.com/user-attachments/assets/3a08ba09-0b6d-42e5-8733-9353d69de44c)

**Comment by ke-a** [comment]
![image](https://github.com/user-attachments/assets/03175150-bafb-4388-aa1b-c18313fa2be1)
in GitHub Codespaces

**Comment by deathbeam** [comment]
Is it possible that you are using different user on windows? can you check `:CopilotChatDebugInfo` and check the config directory and validate github-copilot/hosts.json or apps.json? (dont share the token there, but validate the `user` there)

**Comment by ke-a** [comment]
No, I only have one GitHub user on my computer and it's the same one I used in Codespaces. I checked the `:CopilotChatDebugInfo` and verified both github-copilot/hosts.json and apps.json files- they are correct. I even tried deleting these files and let copilot.lua regenerate them, but the issue persists.

**Comment by deathbeam** [comment]
Hmm, can you check `:checkhealth CopilotChat` and paste here output of the curl check? On both codespaces and windows. Here is how mine looks like on linux for example:

```
- OK curl: curl 8.11.0 (x86_64-pc-linux-gnu) libcurl/8.11.0 OpenSSL/3.4.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.64.0 nghttp3/1.6.0
  Release-Date: 2024-11-06
  Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
  Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

Also output of nvim check, mine:

```
- OK nvim: NVIM v0.11.0-dev-1199+gf55c842ec7
  Build type: Release
  LuaJIT 2.1.1727870382
  Run ":verbose version" for more info
```

**Comment by ke-a** [comment]
On windows:
```
- OK curl: curl 8.9.1 (Windows) libcurl/8.9.1 Schannel zlib/1.3 WinIDN
  Release-Date: 2024-07-31
  Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
  Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
- OK git: git version 2.45.1.windows.
```
output of nvim check:
```NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run ":verbose version" for more info
```
On codespace:
![image](https://github.com/user-attachments/assets/5c9438ed-47f9-45e6-b5dd-0889988b692b)
output of nvim check:
![image](https://github.com/user-attachments/assets/e1fe8edc-9826-4268-803e-42cfc75b17d2)

**Comment by deathbeam** [comment]
hmm i think the windows nvim check you posted is missing nvim version line, can you post that one too?

**Comment by ke-a** [comment]
sorry about that
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run ":verbose version" for more info
```

**Comment by deathbeam** [comment]
Hmm cant easily debug it myself, but could you maybe try this change: https://github.com/CopilotC-Nvim/CopilotChat.nvim/pull/563/files

If you can find where lazyvim stores the plugins can probs just edit it there or use my fork on that branch

**Comment by ke-a** [comment]
It doesn't help. But I noticed something interesting: when I run :CopilotChatModels，it briefly shows this for a split second before showing the final model list without Claude.
![724d6430e844e3539dd92316e2b1105](https://github.com/user-attachments/assets/eeb22ac0-55b3-4451-aa58-0b082999c68d)

**Comment by deathbeam** [comment]
hmm, interesting. i wonder what is github returning. could you maybe try mitmproxy and see the response of the /models call? Or i can add trace log for it, thats probs better

**Comment by deathbeam** [comment]
Ok added trace logging, you can change te log_level to trace like this:

`  log_level = 'trace'`

in opts. Can you try enabling it, then listing the models and then either grabbing the log from messages or go to log file (from :CopilotChatDebugInfo) and paste here?

**Comment by ke-a** [comment]
On Codespace: 
![image](https://github.com/user-attachments/assets/cc44cf8a-24b7-4542-80fa-d430c626d4c9)

 On VSCode (Windows): I confirmed Claude is available there.

I noticed that on Codespace, I can use the plugin immediately without logging in. How does the authentication work in Codespace?

**Comment by deathbeam** [comment]
In codespace the config is grabbed from special environment variable:

```lua
-- loading token from the environment only in GitHub Codespaces
  local token = os.getenv('GITHUB_TOKEN')
  local codespaces = os.getenv('CODESPACES')
  if token and codespaces then
    return token
  end
```

**Comment by ke-a** [comment]
Thank you for letting me know. Now I think I've located the problem. I installed LazyVim on WSL and copied the apps.json content from my Windows to WSL. After running :CopilotChatDebugInfo, I still don't see Claude in the model list. This suggests it might be a token-related issue, since the same apps.json configuration behaves differently in different environments.

**Comment by ke-a** [comment]
But I'm very very curious why the token on my windows would have this issue.

**Comment by ke-a** [comment]
But when I use the token from Codespace in Windows, Claude still doesn't show up.

**Comment by cairijun** [comment]
Had a similar issue but on Linux. It turned out that our corp dev network has a NAT gateway located at Hongkong, which is not one of the Claude's available regions. The Sonnet option shown up after setting up a proxy in one of its available regions.

**Comment by deathbeam** [comment]
> Had a similar issue but on Linux. It turned out that our corp dev network has a NAT gateway located at Hongkong, which is not one of the Claude's available regions. The Sonnet option shown up after setting up a proxy in one of its available regions.

oh interesting, thanks for finding this out, added mention to README. Dont think theres anything else we can do otherwise so closing.
