### ISSUE TITLE
#files is resolving current working directory incorrectly

### ISSUE THREAD

**Issue by lispercat** [CopilotC-Nvim/CopilotChat.nvim#577]
Maybe I don't fully understand the #files prompt behavior, but when I do ``` > #files``` for the first time I can ask the chat what files it can currently see and it gives me some subset of files in my current folder level (even though I would expect it to see my entire c# solution files). 
But if let's say I want to reset the sticky prompt, I open a different file do CopilotChatReset and create another ```> #files``` sticky context, so I would expect it to change its file map to something related to my currently open buffer, but it still lists me the files from the previous session.
Could you provide a little more guidance how to work with ``` #files ``` context and what to expect from it. If your project is big and has many subprojects, what are the expectations from the context?

**Comment by deathbeam** [comment]
`#files` build file map for current working directory (which you can get via `pwd` vim command). so it really depends on what running `:pwd` in the chat buffer returns. even though we had issue similar to this before with git diffs where it wasnt finding the correct working directory, i can probs check if its being changed correctly

**Comment by deathbeam** [comment]
ok fixed it now it should work

**Comment by deathbeam** [comment]
Just delete them from prompt. They are only included if they are in prompt, there is nothing being stored. They are also fully resolved every time you send prompt
