### ISSUE TITLE
Can the `$` model select behaviour be disabled?

### ISSUE THREAD

**Issue by oalders** [CopilotC-Nvim/CopilotChat.nvim#584]
This is making it really hard for me to enter variable names which require a `$`.

https://asciinema.org/a/iYKvCslMyhur52tStG6ceXlii

**Comment by deathbeam** [comment]
With that completion configuration you will probably have issues with the other symbols as well ocassionally so imo its better to either disable autocomplete (there is config option for that) or configure completeopt so it do not auto selects. here is mine for example:

```
vim.o.completeopt = 'menu,menuone,noinsert,fuzzy,popup'
```

(idr if fuzzy and popup are in neovim release so can just skip those 2)
