### ISSUE TITLE
bug(sticky_prompt): cannot use `>` in prompt without sticking

### ISSUE THREAD

**Issue by krishna-bala** [CopilotC-Nvim/CopilotChat.nvim#614]
![image](https://github.com/user-attachments/assets/435fb13a-05a4-4286-ac40-7e81c48e0248)

If the `>` char appears anywhere in the prompt, CopilotChat incorrectly identifies the first `>` as a sticky prompt **_even when it is not the first character in a line_**. 

Escaping the `>` character (`\>`) does not work either.

**Comment by deathbeam** [comment]
Thanks for the report, should be fixed now
