### ISSUE TITLE
Some time Chat in place windows are not closed or closes partially.

### ISSUE THREAD

**Issue by niksingh710** [CopilotC-Nvim/CopilotChat.nvim#65]
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/60490474/9d36aa80-1d75-4b50-9a12-6f0bb18c9c19)
Sometimes these windows are not closed.

Or sometimes this error is thrown.
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/60490474/be083f5d-78d8-4ef7-b2c9-d93be0106721)

I don't feel the current chatInplace UI is intuitive as there is no need of the help section the user can press `?` and get vim's default popup window with the help written in it.

Then only three windows is remaining 
`user input` `selected code snippet` and `output`

this can be inspired from telescope 
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/60490474/729c8699-80c2-4816-a605-7050a82633ea)

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/60490474/307cb5a5-91a4-45b3-8444-4adb5483d37c)

The window should be easily navigable in normal mode via `h,j,k,l` and `q` should close.
And visual select block window should be editable.

**Comment by jellydn** [comment]
Thanks @niksingh710 for the report. We will address this with #66 at the same time.
