### ISSUE TITLE
Programmatically get the currently used model

### ISSUE THREAD

**Issue by louib** [CopilotC-Nvim/CopilotChat.nvim#657]
Is there a way to programmatically obtain the model that is currently used by this plugin? I browsed the docs and the code and couldn't find a way to do that from lua code. I'd like to add the current model to my status bar, so that I can switch between models during the same editing session and easily see which model I'm using.

**Comment by deathbeam** [comment]
You can simpy use `require("CopilotChat").config.model`, that should work (when using CopilotChatModels for switching the model)
