### ISSUE TITLE
Remote branch canary not found in upstream origin

### ISSUE THREAD

**Issue by BaktashGorgani** [CopilotC-Nvim/CopilotChat.nvim#665]
I am Adding CopilotChat to a new install of mine, and I see that the canary branch no longer exists. According to the instructions in the readme, this is the branch we are supposed to use when installing.

```
baky@L3C4V0Z2:~/.config> git clone -b canary https://github.com/CopilotC-Nvim/CopilotChat.nvim
Cloning into 'CopilotChat.nvim'...
fatal: Remote branch canary not found in upstream origin
```

**Comment by jellydn** [comment]
It's on `main` now.

**Comment by jellydn** [comment]
FYI https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/e1e1a54c69eed2fed9baf7fadb05f791ce3f5939
