### ISSUE TITLE
Curl option `--fail-with-body` is unknown

### ISSUE THREAD

**Issue by RomaLzhih** [CopilotC-Nvim/CopilotChat.nvim#677]
![image](https://github.com/user-attachments/assets/312a6890-25ca-4003-b3e8-11a4ab730f8d)
As the figure shows, the plugin seems to call the curl with some wired param?

I am using curl 7.61.1 on linux and nvim 0.10.3 release. 

Any suggestions would be useful. Thanks!

**Comment by deathbeam** [comment]
Should be fixed now (but would recommend updating curl anyway your curl version is super old :d)
