### ISSUE TITLE
Apply doesn't replace the whole file content by the suggestion

### ISSUE THREAD

**Issue by MartinDelille** [CopilotC-Nvim/CopilotChat.nvim#680]
The apply suggestion works great except when copilot suggest just a small code snippet.

For example, I am editing this file: https://github.com/conan-io/conan-center-index/blob/master/recipes/llvm-core/all/conanfile.py

Here is my copilot chat:

```
## User ───

Upgrade libffi to 3.5.1

## Copilot ───

To upgrade `libffi` to version `3.5.1` in your `conanfile.py`, you need to update the version specified in the `requirements` method. Here is the modified section of the file:

def requirements(self):
    if self.options.with_ffi:
        self.requires("libffi/3.5.1")
    if self.options.get_safe("with_libedit"):
        self.requires("editline/3.1")
    if self.options.with_zlib:
        self.requires("zlib/[>=1.2.11 <2]")
    if self.options.with_xml2:
        self.requires("libxml2/[>=2.12.5 <3]")
    if self.options.with_z3:
        self.requires("z3/4.13.0")

This change updates the `libffi` dependency to version `3.5.1`.

## User

```

If I press C-y, the whole file content is replace by the code snippet. I tried to do the same within VSCode and after a few second of processing, it edited properly by replacing only the line https://github.com/conan-io/conan-center-index/blob/master/recipes/llvm-core/all/conanfile.py#L150 by 

```
    self.requires.("libffi/3.5.1")
```

I guess there might be some processing involved so that VSCode cleaverly update the file.

**Comment by deathbeam** [comment]
You need to use /COPILOT_GENERATE prompt, that one will also try to include diff header above the diff which we then parse and replace correct lines

**Comment by MartinDelille** [comment]
That is awesome! Thank you so much!
