### ISSUE TITLE
Prompt window never returns to user input stage when copilot is done

### ISSUE THREAD

**Issue by XavierChanth** [CopilotC-Nvim/CopilotChat.nvim#681]
Whenever I use this tool, I'm left with the loading indicator like this:

![CleanShot 2024-12-09 at 07 37 13@2x](https://github.com/user-attachments/assets/618b5754-8cb9-44ec-b72f-b1de325df1e8)

I can use `require("CopilotChat").ask(input, {...etc})` with vim.fn.input, but this of course is not ideal if I need to pass more context or longer and more complex prompts.

I've tried adding a callback to the setup, and calling vim.notify, I've also tried checking the logs, and they aren't working. I emptied them when debugging to try to get clearer information, and there hasn't been anything added since.

https://gist.github.com/XavierChanth/d8b2b0dc62d8b50261de2ae22e7eb4a1

And my lazy version defaults:
```
  defaults = {
    lazy = true,
    version = "*",
  },
```

Installed version:
```
CopilotChat.nvim
        version 3.3.2
        tag     v3.3.2
        branch  main
        commit  1fe19d1
```

```
copilot.vim
        version 1.41.0
        tag     v1.41.0
        branch  release
        commit  8703812
```

This is on Macos arm64. Any ideas? Or is there some other information that might help debug this issue?

```

**Comment by deathbeam** [comment]
You have outdated plenary.nvim, make sure lazy.nvim reports you are on commit 2d9b061 there.

**Comment by XavierChanth** [comment]
> You have outdated plenary.nvim, make sure lazy.nvim reports you are on commit 2d9b061 there.

Ah, I didn't realize plenary hasn't tagged in a while. Working now, thanks!
