### ISSUE TITLE
`:CopilotChatCommit` prompt contains buffer selection?

### ISSUE THREAD

**Issue by hongzio** [CopilotC-Nvim/CopilotChat.nvim#686]
The quality of the commit message seems lower when using `context.gitdiff` after the update compared to `select.gitdiff` before the update. Could this be because the prompt for the commit message includes the default selection like #buffer?

Is there a prompt option that can be processed without relying on selection?

**Comment by deathbeam** [comment]
you can just override default selection for /Commit if you want and remove the buffer selection (e.g set selection to false)
