### ISSUE TITLE
<C-y> overrides entire file with the diff

### ISSUE THREAD

**Issue by Jomik** [CopilotC-Nvim/CopilotChat.nvim#693]
When prompting for a review or anything like that and hitting `<C-y>` it seems to just replace the buffer with the suggestion, including line numbers.
Before
![image](https://github.com/user-attachments/assets/a5da5764-46e1-408e-b721-1a382c39676a)
after:
![image](https://github.com/user-attachments/assets/527bd261-ab51-40d3-8169-b6400e8539f0)

**Comment by pidgeon777** [comment]
Try again with the Claude Sonnet 3.5 model.

**Comment by deathbeam** [comment]
That depends on your selection, see help how to see it. also use /COPILOT_GENERATE so it generates diff compatible line numbers in output (see README)
