### ISSUE TITLE
Current buffer included with nil context

### ISSUE THREAD

**Issue by omarabid** [CopilotC-Nvim/CopilotChat.nvim#695]
The current buffer is always included. Tried both

```
context = nil,
```

```
context = 'none',
```

Still, the current buffer is still passed to the context.

Edit:

By returning nil for the selection function

```
selection = function(source)
			return nil
end,
```

The context finally disappeared. I am not sure, however, if this is how it is supposed to work.

**Comment by deathbeam** [comment]
It is, if you check default config the default selection is select.visual or select.buffer. 

you can change selection to just select.visual, dont return nil from inside empty fuction
