### ISSUE TITLE
Buffer hangs while responding

### ISSUE THREAD

**Issue by danielefongo** [CopilotC-Nvim/CopilotChat.nvim#696]
I've updated the plugins, but I don't remember which version I was using before. Now, I can't use your plugin because it always hangs when trying to respond.

https://github.com/user-attachments/assets/4f8a1b98-09eb-400f-ac2d-47249bf29df2

Vim version:
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

CopilotChat version (lazy-lock.json):
```json
{ "branch": "main", "commit": "2ebe591cff06018e265263e71e1dbc4c5aa8281e" }
```

CopilotChat selected model: `gpt-4o`

**Comment by deathbeam** [comment]
You have outdated plenary.nvim version, make sure you are on commit 2d9b061 (lazy.nvim should report that somewhere)

**Comment by danielefongo** [comment]
Ty :heart:
