### ISSUE TITLE
Add config to reset the chat before every prompt

### ISSUE THREAD

**Issue by deathbeam** [CopilotC-Nvim/CopilotChat.nvim#73]
Currently I have to constantly use CopilotChatReset, would be nice to have config option for this

**Comment by jellydn** [comment]
Hi @deathbeam I think we could introduce a new flag: `clear_chat_on_new_prompt = false`. Could you work on this one? There is similar feature on this commit https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/8ff6db68eb00f739546db9954e8910f9c6c683e7 

You could join on Discord to discuss if any questions/comments.

**Comment by deathbeam** [comment]
Sure,created a PR @jellydn
