### ISSUE TITLE
On windows with lazy.nvim `:UpdateRemotePlugins` do nothing

### ISSUE THREAD

**Issue by nikita-starostin** [CopilotC-Nvim/CopilotChat.nvim#78]
Hi, I have done the next:

1. run `pip install python-dotenv requests pynvim==0.5.0 prompt-toolkit`
2. copied configuration from the documentation for the `lazy.nvim`
3. restart nvim
4. ensure that copilot chat plugin is loaded
5. run `:UpdateRemotePlugins`
Below you can see the output:

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/57386894/a00609e7-9443-4fcd-aae6-e2d745b5c49d)

#### I have checked that file, it content was:
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/57386894/8c87b6c7-b517-4144-9405-70a05ef20d38)

After restarting the nvim, I have tried few copilot chat commands like `CopilotChatVisual`, but they get errors `command is not defined`.

Then I have updated generated by `UpdateRemotePlugins` empty `rplugin.nvim` with next code
```
call remote#host#RegisterPlugin('python3', ' C:/Users/n.starostin/AppData/Local/nvim-data/lazy/CopilotChat.nvim/rplugin/python3/CopilotChat', [
      \ {'sync': v:false, 'name': 'CopilotChatBuffer', 'type': 'command', 'opts': {'nargs': '1'}},
      \ {'sync': v:false, 'name': 'CopilotChat', 'type': 'command', 'opts': {'nargs': '1'}},
      \ {'sync': v:false, 'name': 'CopilotChatReset', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'CopilotChatVisual', 'type': 'command', 'opts': {'nargs': '1', 'range': ''}},
      \ {'sync': v:false, 'name': 'CopilotChatVsplitToggle', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'CopilotChatInPlace', 'type': 'command', 'opts': {'nargs': '*', 'range': ''}},
      \ {'sync': v:false, 'name': 'CopilotChatAutocmd', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:false, 'name': 'CopilotChatMapping', 'type': 'command', 'opts': {'nargs': '*'}},
     \ ])
```

Now, after nvim restared, when running `:CopilotChat` I see `E471` argument required, and when running, command without args, like `:CopilotChatInPlace` I see the next error

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/57386894/81043254-37ca-477a-8e3d-136d78c35e98)

##### Output from healthcheck
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/57386894/5ad92e20-6d60-4f38-a4d5-99e77389da1b)
**note:** version of python:
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/57386894/b70f21ef-4c42-4569-8785-f1fedcee8195)

**environment**
windows 10 with powershell
python 3.11.5
nvim 0.9.4

**Comment by jellydn** [comment]
Closed by https://github.com/CopilotC-Nvim/CopilotChat.nvim/discussions/27#discussioncomment-8438000

**Comment by nikita-starostin** [comment]
thank you
