### ISSUE TITLE
Copilot Chat is unavailable in certain countries

### ISSUE THREAD

**Issue by Xarmer** [CopilotC-Nvim/CopilotChat.nvim#81]
`
.local/share/nvim/site/pack/packer/start/CopilotChat.nvim/rplugin/python3/CopilotChat/copilot.py", line 197, in _headers
    "authorization": f"Bearer {self.token['token']}",
KeyError: 'token'
`
Output of `:Copilot status`
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/126620895/a7f15bb6-0674-4e0a-b806-14a4128954d1)

Output of `:Copilot version`
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/126620895/43dfd5fb-ca3d-4fca-a546-5968b9f15a58)

Copilot chat version 1.9.0

**Comment by Xarmer** [comment]
`token = os.getenv("COPILOT_TOKEN")` while `echo $COPILOT_TOKEN` is empty. Who should set this variable and when?

**Comment by cjoke** [comment]
I have not find any final solution to this, some tutorials talk about encryption, and make the keys harder to steal, and others , like me self just put them keys in ~/.bashrc like 
``` 
export COPILOT_TOKEN="your_copilot_key_token_here"
```
then when you restart your shell echo $COPILOT_TOKEN will appear. 

in this case (copilot-chat) I already had pre-installed copilot.vim from tpope repo, and did register after installing it with lazy packet manager. there is a plain and nice install description there. Then I did not have to do any registration with copilot-chat plugin.

**Comment by gptlang** [comment]
Could you try to debug with [4741648](https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/474164885007b3d0a5aef6486350b74337e681aa) and see if they give an error message?

**Comment by Xarmer** [comment]
I get this error
```
{'error_details': {'url': 'https://docs.github.com/site-policy/other-site-policies/github-and-trade-controls', 'message': 'At this time, Copilot is not available in your location. You are currently logged in as Xarmer.', 'title': 'Copilot Unavailable', 'notification_id': 'trade_restricted_country'}, 'message': 'Resource not accessible by integrati
on'}
```
but I set proxy in settings 
```
copilot_chat.setup({
  debug = true,
  show_help = "yes",
  proxy = "proxy-that-i-use-with-copilot.tech:3222",
```

**Comment by Xarmer** [comment]
Why is the issue closed despite the fact that the proxy specified in the settings is not used by the plugin?

**Comment by jellydn** [comment]
Hi @Xarmer, do you use `proxy` config as README? Could you share the config here so we could check the issue? Thanks.
